wandb_version: 1

CLI-command:
  desc: null
  value: train.py --model code2vec --max-files-per-dir 16 --max-num-epochs 20
CUDA_VISIBLE_DEVICES:
  desc: null
  value: Not Set
_wandb:
  desc: null
  value:
    cli_version: 0.8.21
    framework: tensorflow
    is_jupyter_run: false
    python_version: 3.6.9
batch_size:
  desc: null
  value: 200
best_model_path:
  desc: null
  value: /home/larumuga/Desktop/Repositories/CodeSearchNet/resources/saved_models/code2vec-2020-02-11-15-18-22_model_best.pkl.gz
code_code_vector_size:
  desc: null
  value: 768
code_context_vector_size:
  desc: null
  value: 768
code_mark_subtoken_end:
  desc: null
  value: false
code_max_num_contexts:
  desc: null
  value: 200
code_max_num_paths:
  desc: null
  value: 200
code_max_num_tokens:
  desc: null
  value: 200
code_path_embedding_size:
  desc: null
  value: 256
code_path_vocab_count_threshold:
  desc: null
  value: 1
code_path_vocab_size:
  desc: null
  value: 100000
code_pct_bpe:
  desc: null
  value: 0.5
code_token_embedding_size:
  desc: null
  value: 256
code_token_vocab_count_threshold:
  desc: null
  value: 10
code_token_vocab_size:
  desc: null
  value: 100000
code_use_bpe:
  desc: null
  value: true
code_use_subtokens:
  desc: null
  value: false
dropout_keep_rate:
  desc: null
  value: 0.9
fraction_using_func_name:
  desc: null
  value: 0.1
gradient_clip:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.01
learning_rate_code_scale_factor:
  desc: null
  value: 1.0
learning_rate_decay:
  desc: null
  value: 0.98
learning_rate_query_scale_factor:
  desc: null
  value: 1.0
loss:
  desc: null
  value: cosine
margin:
  desc: null
  value: 1
max_epochs:
  desc: null
  value: 20
min_len_func_name_for_query:
  desc: null
  value: 12
model-class:
  desc: null
  value: code2vec
momentum:
  desc: null
  value: 0.85
optimizer:
  desc: null
  value: Adam
patience:
  desc: null
  value: 20
query_mark_subtoken_end:
  desc: null
  value: false
query_max_num_tokens:
  desc: null
  value: 30
query_nbow_pool_mode:
  desc: null
  value: weighted_mean
query_pct_bpe:
  desc: null
  value: 0.5
query_random_token_frequency:
  desc: null
  value: 0.0
query_token_embedding_size:
  desc: null
  value: 768
query_token_vocab_count_threshold:
  desc: null
  value: 10
query_token_vocab_size:
  desc: null
  value: 10000
query_use_bpe:
  desc: null
  value: true
query_use_subtokens:
  desc: null
  value: false
run-name:
  desc: null
  value: null
save_folder:
  desc: null
  value: /home/larumuga/Desktop/Repositories/CodeSearchNet/resources/saved_models
seed:
  desc: null
  value: 0
test_folder:
  desc: null
  value: '[/home/larumuga/Desktop/code2vec_features/test]'
train_folder:
  desc: null
  value: '[/home/larumuga/Desktop/code2vec_features/train]'
valid_folder:
  desc: null
  value: '[/home/larumuga/Desktop/code2vec_features/valid]'
